name: Android CI

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build core with Gradle
      run: ./gradlew -x test --stacktrace
    - name: Test core with Gradle
      run: ./gradlew :core:test --stacktrace
    - name: Build examples with Gradle
      run: ./gradlew :examples:build --stacktrace
